apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: spanet-dijets-eval-22022022-
spec:
  entrypoint: main
  volumes:
    - name: eos
      hostPath:
        path: /var/eos
    - name: krb-secret-vol
      secret:
        secretName: krb-secret
  templates:
  - name: main
    steps:
      - - name: 0
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000001.trees_expanded_spanet.h5"
        - name: 1
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000033.trees_expanded_spanet.h5"
        - name: 2
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000039.trees_expanded_spanet.h5"
        - name: 3
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000040.trees_expanded_spanet.h5"
        - name: 4
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000041.trees_expanded_spanet.h5"
        - name: 5
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000042.trees_expanded_spanet.h5"
        - name: 6
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000043.trees_expanded_spanet.h5"
        - name: 7
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000044.trees_expanded_spanet.h5"
        - name: 8
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000045.trees_expanded_spanet.h5"
        - name: 9
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000046.trees_expanded_spanet.h5"
        - name: 10
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000047.trees_expanded_spanet.h5"
        - name: 11
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000048.trees_expanded_spanet.h5"
        - name: 12
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000049.trees_expanded_spanet.h5"
        - name: 13
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000050.trees_expanded_spanet.h5"
        - name: 14
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000051.trees_expanded_spanet.h5"
        - name: 15
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000052.trees_expanded_spanet.h5"
        - name: 16
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000053.trees_expanded_spanet.h5"
        - name: 17
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000054.trees_expanded_spanet.h5"
        - name: 18
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000055.trees_expanded_spanet.h5"
        - name: 19
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_r10724_r10726_p4355.27356775._000056.trees_expanded_spanet.h5"
        - name: 20
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000002.trees_expanded_spanet.h5"
        - name: 21
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000003.trees_expanded_spanet.h5"
        - name: 22
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000004.trees_expanded_spanet.h5"
        - name: 23
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000005.trees_expanded_spanet.h5"
        - name: 24
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000006.trees_expanded_spanet.h5"
        - name: 25
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000007.trees_expanded_spanet.h5"
        - name: 26
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000008.trees_expanded_spanet.h5"
        - name: 27
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000009.trees_expanded_spanet.h5"
        - name: 28
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000010.trees_expanded_spanet.h5"
        - name: 29
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000011.trees_expanded_spanet.h5"
        - name: 30
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000012.trees_expanded_spanet.h5"
        - name: 31
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000013.trees_expanded_spanet.h5"
        - name: 32
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000018.trees_expanded_spanet.h5"
        - name: 33
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000019.trees_expanded_spanet.h5"
        - name: 34
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000020.trees_expanded_spanet.h5"
        - name: 35
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000021.trees_expanded_spanet.h5"
        - name: 36
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000022.trees_expanded_spanet.h5"
        - name: 37
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000023.trees_expanded_spanet.h5"
        - name: 38
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000025.trees_expanded_spanet.h5"
        - name: 39
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000027.trees_expanded_spanet.h5"
        - name: 40
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000028.trees_expanded_spanet.h5"
        - name: 41
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000029.trees_expanded_spanet.h5"
        - name: 42
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000030.trees_expanded_spanet.h5"
        - name: 43
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000031.trees_expanded_spanet.h5"
        - name: 44
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000032.trees_expanded_spanet.h5"
        - name: 45
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000034.trees_expanded_spanet.h5"
        - name: 46
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000035.trees_expanded_spanet.h5"
        - name: 47
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000036.trees_expanded_spanet.h5"
        - name: 48
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000037.trees_expanded_spanet.h5"
        - name: 49
          template: base
          arguments:
            parameters:
            - name: input
              value: "/eos/atlas/atlascerngroupdisk/phys-susy/RPV_mutlijets_ANA-SUSY-2019-24/ntuples/tag/input/mc16e/dijets_expanded/python/JZ2/user.jbossios.364702.e7142_e5984_s3126_s3136_r10724_r10726_p4355.27356775._000038.trees_expanded_spanet.h5"
  - name: base
    inputs:
      parameters:
      - name: input
    container:
      image: gitlab-registry.cern.ch/jbossios/docker-images/atlas-spanet-jona-dijets-test
      envFrom:
      - configMapRef:
          name: userid-configmap
      volumeMounts:
      - name: eos
        mountPath: /eos
      - name: krb-secret-vol
        mountPath: /secret/krb-secret-vol
      command: ["/bin/sh","-c"]
      args: ["ls -l; python3 /spanet_dijets_eval.py -i {{inputs.parameters.input}}"]
